version: '3.1'
services:
  db:
    image: postgres:14.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgresspa55
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  # cache:
  #   image: redis:6.2.6
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./redis.conf:/usr/local/etc/redis/redis.conf
  #   command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

volumes:
  pgdata: null
